name: "Lock and Unlock the Repo Durimg the Migration"
description: "Provide the source and target organization details for the migration."
title: "Migrate Secrets and Variables for {{source_org}}"
labels:
  - migration
  - automation

body:
  - type: input
    id: source_org
    attributes:
      label: "Source Organization"
      description: "Enter the name of the source organization"
      placeholder: "e.g., sam-org1"
    validations:
      required: true

  - type: input
    id: source_repo
    attributes:
      label: "Source Repository"
      description: "Enter the name of the source Repository"
      placeholder: "e.g., s_repo1"

  - type: input
    id: Target_Org
    attributes:
      label: "target otg takoten selection"
      description: "Select if this migration is for organization-level secrets
                  Note: if you are using the organization level all the repositories under the or will alos be covered."
      options:
        - "mgmri-dge"
        - "mgmri-commerce"
    validations:
      required: true

  - type: input
    id: target_repo
    attributes:
      label: "Target Repository"
      description: "Enter the name of the target Repository"
      placeholder: "e.g., s_repo1"

  - type: dropdown
    id: migration_level
    attributes:
      label: "Migration Level"
      description: "Select if this migration is for organization-level secrets
                  Note: if you are using the organization level all the repositories under the or will alos be covered."
      options:
        - "Organization"
        - "Repository"
  
  - type: dropdown
    id: locksourcerepo
    attributes:
      label: "Lock Source Repo"
      description: Please select the Lock Repo for the Source repository after they have been migrated
      options:
        - 'Yes'
        - 'No'


